# Generated by Django 2.2.6 on 2019-10-02 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bauthor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='book_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='buser',
            field=models.ForeignKey(default='', on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='semester',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='bname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
