# Generated by Django 2.2.6 on 2019-10-02 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20191002_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='buser',
            field=models.ForeignKey(default='pratyush', on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
