# Generated by Django 2.2.6 on 2019-10-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20191003_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='branch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
