# Generated by Django 2.2.6 on 2019-10-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_book_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='branch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
    ]
