# Generated by Django 2.2.6 on 2019-10-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_anything'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anything',
        ),
    ]
