# Generated by Django 2.2.6 on 2019-10-21 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_remove_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(auto_now_add=True,),
            preserve_default=False,
        ),
    ]
