# Generated by Django 2.2.6 on 2019-10-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_book_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
    ]
