# Generated by Django 2.2.6 on 2019-10-21 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_remove_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 22, 2, 17, 28, 3704)),
        ),
    ]
